chore: updated dependencies for backend workflow

diff --git a/.github/workflows/build-deploy-backend.yml b/.github/workflows/build-deploy-backend.yml
--- a/.github/workflows/build-deploy-backend.yml
+++ b/.github/workflows/build-deploy-backend.yml
@@ -93,18 +93,18 @@ jobs:
       packages: write
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        uses: docker/setup-buildx-action@v4
       - name: Log in to the Container registry
-        uses: docker/login-action@v3
+        uses: docker/login-action@v4
         with:
           registry: ghcr.io
           username: "${{ github.repository_owner }}"
           password: "${{ secrets.GITHUB_TOKEN }}"
       - name: "Extract metadata (tags, labels) for Docker"
         id: meta
-        uses: docker/metadata-action@v5
+        uses: docker/metadata-action@v6
         with:
           images: >
             ghcr.io/${{ github.repository }}-backend # The container is located at the repository
@@ -115,7 +115,7 @@ jobs:
             type=raw,value={{sha}}
             type=ref,event=branch
       - name: Build and push Docker image
-        uses: docker/build-push-action@v5
+        uses: docker/build-push-action@v7
         with:
           context: .
           file: ./Dockerfile_Backend
@@ -144,10 +144,18 @@ jobs:
       PUBLIC_URL: "${{ needs.generate_workflow_vars.outputs.PUBLIC_URL }}"
       default_port: "${{ needs.setup_workflow_env.outputs.default_port}}"
   clean_up_cache:
+    permissions:
+      actions: write
+      contents: read
     needs:
       - build-and-push-image
     runs-on: ubuntu-latest
-    steps:
-      - uses: MyAlbum/purge-cache@v2
-        with:
-          max-age: 604800
+    name: Purge Cache for current branch
+    env:
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    run: |
+      echo "Finding caches for branch: ${{ github.ref }}"
+      # Fetch cache ids for current branch and delete them
+      gh cache list --ref ${{ github.ref }} --json id --jq '.[].id' | xargs -I {} gh cache delete {} || echo "No caches found or failed to delete."
+
+      echo "Cache purge complete."
